spring:
   port: 8878
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: root
    password: taotao521
    driver-class-name: com.mysql.jdbc.Driver


  redis:
    host:
    database:
    password:
    port:
    timeout:
    pool:
      max-idle:
      max-active:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

