server:
  port: 8878
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: taotao521
    url: jdbc:mysql://localhost:3306/didifood?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    type: com.alibaba.druid.pool.DruidDataSource


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  config: classpath:log4j2.xml

