server:
  port: 8889

spring:
  application:
    name: item
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true


